name: Django CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run
      run: |
        git checkout develop
        apt install -y binutils make m4 perl python3 tar bc gcc g++ ca-certificates
        export MAKE="make -j4"
        ./configure
        make
        tree ./

