name: Django CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: fedora-34

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run
      run: |
        git checkout develop
        dnf install -y binutils make m4 python3 perl perl-ExtUtils-MakeMaker tar gcc gcc-c++ findutils which diffutils perl-IPC-Cmd
        export MAKE="make -j4"
        ./configure
        make
        tree ./

